#covered topic
Numpy - Nd Array Object.

Numpy - Data Types.

Numpy - Array Attributes.

Numpy - Array Creation Routines.

Numpy - Array From Existing.

Data Array From Numerical Ranges.

Numpy - Indexing & Slicing.

Numpy - Advanced Indexing.

Numpy - Broadcasting.

Numpy - Iterating Over Array

Numpy - Array Manipulation.

Numpy - Conditional operations with all and any

Numpy - String Functions.

Numpy - Mathematical Functions.

Numpy - Arithmetic Operations.

Numpy - Statistical Functions.

Sort, Search & Counting Functions.

Numpy - Linear Algebra


In [2]:
import numpy as np
A=np.array([[1,2,3,4],
            [5,6,7,8]
            ])
B=np.array([[1,2,3,4],
            [5,6,7,8],
            [1,2,3,4],
            [1,2,3,4]
            ])
d=np.dot(A,B)
print(d)

[[ 18  28  38  48]
 [ 50  76 102 128]]


In [91]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
d = np.dot(A, B)
d1 = np.linalg.inv(d)
print(d1)


[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [7]:
t=np.transpose(d)
print(t)

[[ 18  50]
 [ 28  76]
 [ 38 102]
 [ 48 128]]


# Numpy Questions

### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1 & 3rd row 1
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [15]:
arr=np.random.randint(1,21,size=(5,5))
print(arr)
print(arr[:,2])
arr[:,2]=1
print(arr)

[[15 13 17  1 19]
 [17 10  5 10  9]
 [ 6 16 14 14  4]
 [ 9  9 19 19  9]
 [ 7 11 19 10 13]]
[17  5 14 19 19]
[[15 13  1  1 19]
 [17 10  1 10  9]
 [ 6 16  1 14  4]
 [ 9  9  1 19  9]
 [ 7 11  1 10 13]]


In [27]:
arr=np.random.randint(1,21,size=(5,5))
print(arr)
arr[2:3,:]=1
print(arr)


[[ 2 11  6 10  7]
 [18 13  5 16 18]
 [ 8 10 10 20 15]
 [15  2 19 17  5]
 [20  9 19  6 15]]
[[ 2 11  6 10  7]
 [18 13  5 16 18]
 [ 1  1  1  1  1]
 [15  2 19 17  5]
 [20  9 19  6 15]]


In [21]:
arr1=np.random.randint(1,17,size=(4,4))
print(arr1)

np.fill_diagonal(arr1,0)
print(arr1)

[[10  9  2 10]
 [ 8  9  4  2]
 [ 4  4  2  4]
 [ 7  5 16  9]]
[[ 0  9  2 10]
 [ 8  0  4  2]
 [ 4  4  0  4]
 [ 7  5 16  0]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [29]:
arr=np.random.randint(1,36,size=(6,6))
print(arr)
arr_3_5=arr[2:5,1:4]
print(arr_3_5)

[[26 19 17 22  9 23]
 [14 11 15 14 35 13]
 [24 31 19  1 30 22]
 [12 26 19  5  1  8]
 [32 19 10 21 17  5]
 [16 13  6  2 17 23]]
[[31 19  1]
 [26 19  5]
 [19 10 21]]


In [33]:
arr=np.random.rand(5,5)
print(arr)
arr_border1=arr[0,:]
arr_border2=arr[-1,:]
left_border=arr[1:4,0]
right_border=arr[1:4,-1]
arr_border=np.concatenate((arr_border1,arr_border2,left_border,right_border))
print(arr_border)


[[0.99551977 0.74740147 0.60006807 0.25030302 0.33262888]
 [0.37296921 0.90929452 0.63334231 0.7983621  0.48823163]
 [0.27794062 0.96556322 0.20331216 0.65758448 0.4292707 ]
 [0.99414718 0.09755055 0.18280554 0.49085571 0.68229326]
 [0.53806408 0.07466956 0.04354059 0.13394448 0.77808056]]
[0.99551977 0.74740147 0.60006807 0.25030302 0.33262888 0.53806408
 0.07466956 0.04354059 0.13394448 0.77808056 0.37296921 0.27794062
 0.99414718 0.48823163 0.4292707  0.68229326]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [35]:
arr1=np.random.randint(1,50,size=(3,4))
arr2=np.random.randint(1,50,size=(3,4))
arr_add=arr1+arr2
print(arr_add)
arr_sub=arr1-arr2
print(arr_sub)
arr_mul=arr1*arr2
print(arr_mul)
arr_div=arr1/arr2
print(arr_div)

[[75 27 47 85]
 [86 71 70 62]
 [59 73 44 46]]
[[ -9 -13  11  -9]
 [ -4  17  14 -14]
 [ 13  -7  20 -28]]
[[1386  140  522 1786]
 [1845 1188 1176  912]
 [ 828 1320  384  333]]
[[0.78571429 0.35       1.61111111 0.80851064]
 [0.91111111 1.62962963 1.5        0.63157895]
 [1.56521739 0.825      2.66666667 0.24324324]]


In [38]:
arr1=np.random.randint(1,17,size=(4,4))
row_sum=np.sum(arr1,axis=1)
col_sum=np.sum(arr1,axis=0)
print(arr1)
print(f'row wise sum {row_sum}')
print(f'column wise sum {col_sum}')

[[ 5  6  8  6]
 [13  5 15  8]
 [14 13 10  9]
 [ 2  9 10 11]]
row wise sum [25 41 46 32]
column wise sum [34 33 43 34]


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [46]:
arr=np.random.rand(5,5)
print(arr)
mean=np.mean(arr)
print(f'mean {mean:.2f}')
median=np.median(arr)
print(f'median {median:.2f}')
std=np.std(arr)
print(f'standard deviation {std:.2f}')
var=np.var(arr)
print(f'variance {var:.2f}')


[[0.27296928 0.29093741 0.81670172 0.86371092 0.44903014]
 [0.21751984 0.26320767 0.0996786  0.61683712 0.27414414]
 [0.24702158 0.60328037 0.09387059 0.24024208 0.19413964]
 [0.75290227 0.4422717  0.21955454 0.23378464 0.55853273]
 [0.46969688 0.65423539 0.30222083 0.57117993 0.10436101]]
mean 0.39
median 0.29
standard deviation 0.22
variance 0.05


### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [49]:
arr=np.random.randint(1,25,size=(3,3))
arr1=np.random.randint(1,25,size=(3,))
print(arr)
print(arr1)
print(arr+arr1)

[[21 17  7]
 [19  5  7]
 [17 19 23]]
[ 4  1 18]
[[25 18 25]
 [23  6 25]
 [21 20 41]]


In [51]:
print(arr1[np.newaxis,:])
print(arr1[:,np.newaxis])

[[21 22 11  9]]
[[21]
 [22]
 [11]
 [ 9]]


In [89]:
arr=np.random.randint(1,25,size=(4,4))
arr1=np.random.randint(1,25,size=(4,))
arr2 = arr1.reshape(4, 1) # row =3, col = 1
print(arr)
print(arr1)
print(arr - arr2)

[[ 3 22  4 18]
 [10  3 23  6]
 [ 7 16 18 20]
 [20 14 21 15]]
[17 14 11 15]
[[-14   5 -13   1]
 [ -4 -11   9  -8]
 [ -4   5   7   9]
 [  5  -1   6   0]]


### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [56]:
A=np.array([[1,2,3,4],
            [5,6,7,8]
            ])
B=np.array([[1,2,3,4],
            [5,6,7,8],
            [1,2,3,4],
            [1,2,3,4]
])
print(np.dot(A,B))

[[ 18  28  38  48]
 [ 50  76 102 128]]


### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [58]:
arr=np.random.randint(1,10,size=(3,3))
print(arr)
print(arr.reshape(1,9))
print(arr.reshape(9,1))

[[2 1 6]
 [5 2 6]
 [3 3 9]]
[[2 1 6 5 2 6 3 3 9]]
[[2]
 [1]
 [6]
 [5]
 [2]
 [6]
 [3]
 [3]
 [9]]


In [59]:
arr=np.random.randint(1,10,size=(5,5,5))
print(arr)
flatten_arr=arr.flatten()
print(flatten_arr)
print(flatten_arr.reshape(5,5,5))

[[[2 2 6 8 6]
  [3 5 9 3 7]
  [9 2 2 9 2]
  [6 8 4 7 1]
  [4 5 8 1 4]]

 [[2 4 5 4 9]
  [5 4 1 9 6]
  [5 1 4 7 1]
  [4 9 1 2 5]
  [4 5 7 6 2]]

 [[1 5 6 4 9]
  [1 6 4 8 4]
  [5 6 5 6 1]
  [2 7 9 5 9]
  [9 4 3 1 6]]

 [[8 1 3 7 9]
  [7 3 9 7 5]
  [9 6 1 2 3]
  [1 3 8 6 8]
  [7 3 9 6 7]]

 [[3 1 5 2 6]
  [5 4 8 4 5]
  [6 4 4 5 5]
  [9 3 1 9 3]
  [5 8 4 9 7]]]
[2 2 6 8 6 3 5 9 3 7 9 2 2 9 2 6 8 4 7 1 4 5 8 1 4 2 4 5 4 9 5 4 1 9 6 5 1
 4 7 1 4 9 1 2 5 4 5 7 6 2 1 5 6 4 9 1 6 4 8 4 5 6 5 6 1 2 7 9 5 9 9 4 3 1
 6 8 1 3 7 9 7 3 9 7 5 9 6 1 2 3 1 3 8 6 8 7 3 9 6 7 3 1 5 2 6 5 4 8 4 5 6
 4 4 5 5 9 3 1 9 3 5 8 4 9 7]
[[[2 2 6 8 6]
  [3 5 9 3 7]
  [9 2 2 9 2]
  [6 8 4 7 1]
  [4 5 8 1 4]]

 [[2 4 5 4 9]
  [5 4 1 9 6]
  [5 1 4 7 1]
  [4 9 1 2 5]
  [4 5 7 6 2]]

 [[1 5 6 4 9]
  [1 6 4 8 4]
  [5 6 5 6 1]
  [2 7 9 5 9]
  [9 4 3 1 6]]

 [[8 1 3 7 9]
  [7 3 9 7 5]
  [9 6 1 2 3]
  [1 3 8 6 8]
  [7 3 9 6 7]]

 [[3 1 5 2 6]
  [5 4 8 4 5]
  [6 4 4 5 5]
  [9 3 1 9 3]
  [5 8 4 9 7]]]


### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [83]:
arr=np.random.randint(1,100,size=(4,4))
arr[arr>10]=100
print(arr)

[[100 100 100 100]
 [100 100   4 100]
 [  3 100   6 100]
 [100 100 100 100]]


# Problem Solving


Easy
https://www.deep-ml.com/problems/3

In [84]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    #Write your code here and return a python list after reshaping by using numpy's tolist() method
    arr = np.array(a)
    if arr.size != new_shape[0] * new_shape[1]:
        return []
    arr = arr.reshape(new_shape[0],new_shape[1])
    return arr.tolist()

Easy
https://www.deep-ml.com/problems/5

In [ ]:
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    arr = np.array(matrix)
    arr = arr * scalar
	return arr.tolist()

Easy
https://www.deep-ml.com/problems/35

In [ ]:
import numpy as np

def make_diagonal(x):
	# Your code here
	return np.diag(x)

Easy
https://www.deep-ml.com/problems/83


In [ ]:
import numpy as np

def calculate_dot_product(vec1, vec2) -> float:
	"""
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	"""
	# Your code here
	return np.dot(vec1, vec2)

Easy
https://www.deep-ml.com/problems/121